apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage
  annotations:
    github.com/project-slug: backstage/backstage
  links:
    - url: https://backstage.io
      title: Official website
      icon: dashboard
      type: URL
  tags:
    - typescript
spec:
  type: website
  owner: Schabo
  lifecycle: experimental
